pipeline {
    agent {
        dockerContainer { image 'jenkins/inbound-agent:alpine' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'echo "Hello World!"'
            }
        }
    }
}